cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy_prod

build:
  stage: build
  image: node:12.18.3
  script:
    - npm install

deploy_production:
  image: node:12.18.3
  stage: deploy_prod
  script:
    - git push https://$HEROKU_USER:$HEROKU_API_KEY@git.heroku.com/ds-assignment-2-consumer.git HEAD:master
    - echo "Deployed to production"
  environment:
    name: production
    url: https://ds-assignment-2-consumer.herokuapp.com
  only:
    - master
